export class ExportService {
  /**
   * Formats raw analysis data into structured Markdown for downloads.
   */
  static generateMarkdownReport(data: {
    title: string;
    score: number;
    category: string;
    hooks: Array<{ style: string; text: string }>;
    seoDescription: string;
  }): string {
    const hooksText = data.hooks
      .map((h) => `- **${h.style} Hook:** ${h.text}`)
      .join('\n');

    return `# Script Analysis Report: ${data.title}

**Category:** ${data.category}
**Viral Score:** ${data.score}/100

---

## 🎯 High-Converting Hooks
${hooksText}

---

## 📝 Optimized SEO Description
\`\`\`
${data.seoDescription}
\`\`\`

---
*Generated by CreatorPilot AI*
`;
  }

  /**
   * Converts analysis record into downloadable JSON format.
   */
  static generateJSONReport(data: unknown): string {
    return JSON.stringify(data, null, 2);
  }
}